# Generated by Django 4.1.1 on 2022-09-14 13:45

from django.db import migrations, models
import django.db.models.deletion
import imagens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemHistorico',
            fields=[
                ('id_imagem_historico', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=imagens.models.imagem_historico)),
                ('id_historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='historicos.historicos')),
            ],
        ),
    ]
